name: Format
on:
  push:
    branches: [main]
  pull_request:
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v21
      - name: Format check
        run: nix fmt -- --ci
