name: Label CMS PRs
on:
  pull_request:
    types: [opened]
jobs:
  label:
    name: Add auto-merge label
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'cms/')
    permissions:
      pull-requests: write
    steps:
      - name: Add auto-merge label
        run: gh pr edit "${{ github.event.pull_request.number }}" --add-label "auto-merge"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
